- name: Download deb package
  get_url:
    url="https://dl.grafana.com/oss/release/grafana_{{ version }}_amd64.deb"
    dest="/var/tmp/grafana_{{ version }}_amd64.deb"

- name: Install Grafana 
  apt: deb="/var/tmp/grafana_{{ version }}_amd64.deb"

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "Check if Grafana is accessible."
  uri:
    url: http://{{ groups.grafana.0 }}:3000
    method: GET
    status_code: 200
